name: Build

on:
  push:
  pull_request:
  schedule:
    # Weekly build (on saturday)
    - cron: '0 0 * * 6'

jobs:
  # build-ubuntu:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: recursive

  #   - name: Install various apt dependencies
  #     run: sudo apt-get install build-essential cmake meson ninja-build nlohmann-json3-dev pkg-config libssl-dev libsdl2-dev

  #   - name: Configure Meson
  #     run: meson setup ${{github.workspace}}/build 

  #   - name: Build
  #     # Build your program with the given configuration
  #     run: meson compile -C ${{github.workspace}}/build
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: brew install gcc
      - run: pip install meson ninja
      - run: meson setup ${{github.workspace}}/build
        env:
          CC: gcc
      - run: meson compile -C ${{github.workspace}}/build -v
      
